default:
  cache:
    key: "$CI_COMMIT_REF_SLUG"
    paths:
      - node_modules/
  before_script:
    - bun install

build-storybook:
  stage: build
  script:
    - bun run build:storybook
  artifacts:
    paths:
      - storybook

build-package:
  stage: build
  script:
    - bun run build:package
  artifacts:
    paths:
      - dist

release-storybook:
  stage: release
  script:
    - bun run release:storybook
  artifacts:
    paths:
      - storybook
  only:
    - master
