default:
  cache:
    key: "$CI_COMMIT_REF_SLUG"
    paths:
      - node_modules/
  before_script:
    - bun install

build-storybook:
  stage: build
  script:
    - bun run build:storybook
  artifacts:
    paths:
      - storybook

build-package:
  stage: build
  script:
    - bun run build:package
  artifacts:
    paths:
      - dist

publish-package:
  stage: deploy
  before_script:
    - corepack enable
    - yarn set version stable
  script:
    - yarn npm publish --set-version 1.0.0-develop.1
