yarnPath: .yarn/releases/yarn-4.4.0.cjs

npmScopes:
  hi-infrastructure:
    npmPublishRegistry: "http://gitlab-instance/projects/${CI_PROJECT_ID}/packages/npm/"
    npmAlwaysAuth: true
    npmAuthToken: "${CI_JOB_TOKEN}"

unsafeHttpWhitelist:
  - gitlab-instance