yarnPath: .yarn/releases/yarn-4.4.0.cjs
npmScopes:
  hi-infrastructure:
    npmPublishRegistry: "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/npm/"
    npmAlwaysAuth: true
    npmAuthToken: "${CI_JOB_TOKEN}"
    npmRegistryServer: "http://localhost:2080/api/v4/packages/npm"
